# Generated by Django 4.1.7 on 2023-03-22 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_career'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='msg',
            field=models.TextField(default=None),
        ),
    ]
