# Generated by Django 4.1.7 on 2023-03-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_career_msg'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarriageEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bride_groom', models.CharField(blank=True, max_length=500, null=True)),
                ('function', models.CharField(blank=True, max_length=500, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('number_of_room', models.CharField(blank=True, max_length=500, null=True)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('guest_capacity', models.CharField(blank=True, max_length=500, null=True)),
                ('number_of_night', models.CharField(blank=True, max_length=500, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=500, null=True)),
                ('email_address', models.CharField(blank=True, max_length=500, null=True)),
                ('msg', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=300, null=True)),
                ('hotel_name', models.CharField(blank=True, max_length=300, null=True)),
                ('mobile', models.CharField(blank=True, max_length=300, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('email', models.CharField(blank=True, max_length=300, null=True)),
                ('room', models.CharField(blank=True, max_length=300, null=True)),
                ('msg', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
