# Generated by Django 4.2.1 on 2023-05-09 04:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_marriageevents_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='EventSlider/')),
            ],
        ),
        migrations.CreateModel(
            name='EventText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('desc', ckeditor.fields.RichTextField(blank=True, default=None, null=True)),
            ],
        ),
    ]
