from django.contrib import admin
from .models import *
# Register your models here.

admin.site.register(Slider)
admin.site.register(OfferSlider)
# admin.site.register(Menu)
# admin.site.register(SubMenu)
# admin.site.register(AboutCategory)
# admin.site.register(EventCategory)
admin.site.register(BlogCategory)
# admin.site.register(OccasionCategory)
admin.site.register(GalleryCategory)
admin.site.register(GalleryImage)
admin.site.register(GalleryVideo)
admin.site.register(Blog)
admin.site.register(BlogComment)
# admin.site.register(Event)
# admin.site.register(Testimonial)
# admin.site.register(AddBudget)
# admin.site.register(AddFacility)
admin.site.register(Hotel)
admin.site.register(VenuCategory)
admin.site.register(State)
admin.site.register(City)
admin.site.register(Venu)
admin.site.register(VenuImages)
admin.site.register(Reservation)
# admin.site.register()
