# Generated by Django 4.2.1 on 2023-05-22 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_venucategory_img'),
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gallery',
            new_name='GalleryHotel',
        ),
    ]
