# Generated by Django 4.2.1 on 2023-05-23 06:46

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_hotel_accommodation_hotel_contact_details'),
        ('hotels', '0002_rename_gallery_galleryhotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='hotel/content/')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('txt', ckeditor.fields.RichTextField(blank=True, default=None, null=True)),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.hotel')),
            ],
        ),
    ]
