# Generated by Django 4.2.1 on 2023-05-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_hotelcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelcontent',
            name='heading',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
