# Generated by Django 4.2.1 on 2023-05-24 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_hotelcontent_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='dining',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
