# Generated by Django 4.2.1 on 2023-05-24 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_dining_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='offer1',
            new_name='short',
        ),
        migrations.RemoveField(
            model_name='package',
            name='offer2',
        ),
    ]
