# Generated by Django 4.2.1 on 2023-05-24 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_rename_state_hotelcontact_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='slug',
            field=models.SlugField(auto_created=True, blank=True, null=True, unique=True),
        ),
    ]
