# Generated by Django 4.1.7 on 2023-03-24 04:36

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutCategory',
        ),
        migrations.DeleteModel(
            name='AddBudget',
        ),
        migrations.RemoveField(
            model_name='event',
            name='cat',
        ),
        migrations.DeleteModel(
            name='SimilarCategory',
        ),
        migrations.RemoveField(
            model_name='submenu',
            name='menu',
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
        migrations.RemoveField(
            model_name='venu',
            name='email',
        ),
        migrations.RemoveField(
            model_name='venu',
            name='end_time_evening',
        ),
        migrations.RemoveField(
            model_name='venu',
            name='end_time_morning',
        ),
        migrations.RemoveField(
            model_name='venu',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='venu',
            name='max_capacity',
        ),
        migrations.RemoveField(
            model_name='venu',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='venu',
            name='meta_keyword',
        ),
        migrations.RemoveField(
            model_name='venu',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='venu',
            name='min_capacity',
        ),
        migrations.RemoveField(
            model_name='venu',
            name='non_veg_plate',
        ),
        migrations.RemoveField(
            model_name='venu',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='venu',
            name='start_time_evening',
        ),
        migrations.RemoveField(
            model_name='venu',
            name='start_time_morning',
        ),
        migrations.RemoveField(
            model_name='venu',
            name='veg_plate',
        ),
        migrations.RemoveField(
            model_name='venu',
            name='venue_policy',
        ),
        migrations.AddField(
            model_name='hotel',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='hotel/'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='summary',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='venu',
            name='check_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venu',
            name='check_out',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='AddFacility',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='EventCategory',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='SubMenu',
        ),
    ]
