# Generated by Django 4.1.7 on 2023-03-24 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_aboutcategory_delete_addbudget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='summary',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
