# Generated by Django 4.1.7 on 2023-03-24 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_hotel_summary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OccasionCategory',
        ),
        migrations.AddField(
            model_name='venu',
            name='breakfast',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='venu',
            name='gym',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='venu',
            name='parking',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='venu',
            name='pool',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='venu',
            name='reception',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='venu',
            name='wifi',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
