# Generated by Django 4.1.7 on 2023-03-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_occasioncategory_venu_breakfast_venu_gym_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venu',
            name='location',
        ),
        migrations.AlterField(
            model_name='venu',
            name='breakfast',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Break Fast'),
        ),
        migrations.AlterField(
            model_name='venu',
            name='parking',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Parking'),
        ),
        migrations.AlterField(
            model_name='venu',
            name='pool',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Swiming Pool'),
        ),
        migrations.AlterField(
            model_name='venu',
            name='wifi',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Wi Fi'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
