# Generated by Django 4.1.7 on 2023-03-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_venu_location_alter_venu_breakfast_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venu',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
