# Generated by Django 4.2.1 on 2023-05-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_venu_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='venucategory',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='vanu/category/'),
        ),
    ]
