# Generated by Django 4.2.1 on 2023-05-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_venucategory_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='breakfast',
            field=models.BooleanField(default=False, verbose_name='Break Fast'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='gym',
            field=models.BooleanField(default=False, verbose_name='GYM'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='parking',
            field=models.BooleanField(default=False, verbose_name='Parking'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='pool',
            field=models.BooleanField(default=False, verbose_name='Pool'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='reception',
            field=models.BooleanField(default=False, verbose_name='Reception'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='room_service',
            field=models.BooleanField(default=False, verbose_name='Room Service'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='wifi',
            field=models.BooleanField(default=False, verbose_name='Wi-Fi'),
        ),
    ]
